给IRepository增加MongoDb Update和UpdateRange的实现
SugarChat/SugarChat pull request #19
Opened 2021-05-08 02:19 UTC by huangkemeng

2021-05-09 11:47 UTC, mayuanyang requested changes
有错别字，另外看看CreatedDate是否一起处理？另外虽然不是这个PR本身，但是Respoistory里面的aync方法也一起检查一下？

![image](https://user-images.githubusercontent.com/3387099/117571013-9c086e00-b081-11eb-8ef5-4fbc25306313.png)

2021-05-09 11:47 UTC, mayuanyang commented on src/SugarChat.Core/Domain/IEntity.cs
> +        DateTimeOffset LastModifyDate { get; set; }
我们现在有没有地方定义了CreatedDate？

2021-05-09 11:47 UTC, mayuanyang commented on src/SugarChat.MongoDb/MongoDbRepository.cs
> +        public Task UpdateRangAsync<T>(IEnumerable<T> entities, CancellationToken cancellationToken = default) where T : class, IEntity
有错别字，应该是UpdateRangeAsync

2021-05-09 11:47 UTC, mayuanyang commented on src/SugarChat.MongoDb/MongoDbRepository.cs
> +            if (entities?.Any() == true)
可能不需要 == true ？

2021-05-09 14:07 UTC, huangkemeng commented on src/SugarChat.MongoDb/MongoDbRepository.cs
> +            if (entities?.Any() == true)
需要的～

2021-05-09 14:08 UTC, huangkemeng commented on src/SugarChat.MongoDb/MongoDbRepository.cs
> +        public Task UpdateRangAsync<T>(IEnumerable<T> entities, CancellationToken cancellationToken = default) where T : class, IEntity
ok，将会修改～

2021-05-09 14:08 UTC, huangkemeng commented on src/SugarChat.Core/Domain/IEntity.cs
> +        DateTimeOffset LastModifyDate { get; set; }
有定义的，需要拉到IEntity吗

2021-05-09 14:09 UTC, huangkemeng commented
> 有错别字，另外看看CreatedDate是否一起处理？另外虽然不是这个PR本身，但是Respoistory里面的aync方法也一起检查一下？
> 
> ![image](https://user-images.githubusercontent.com/3387099/117571013-9c086e00-b081-11eb-8ef5-4fbc25306313.png)
> 
这里没有异步方法，我认为也这里可以不用异步方法～

2021-05-11 12:01 UTC, JiaZhenLin commented
> > 有错别字，另外看看CreatedDate是否一起处理？另外虽然不是这个PR本身，但是Respoistory里面的aync方法也一起检查一下？
> > ![image](https://user-images.githubusercontent.com/3387099/117571013-9c086e00-b081-11eb-8ef5-4fbc25306313.png)
> 
> 这里没有异步方法，我认为也这里可以不用异步方法～

MongoDB.Driver.Linq 异步方法在这个命名空间下 @huangkemeng

2021-05-12 08:13 UTC, huangkemeng commented
> > > 有错别字，另外看看CreatedDate是否一起处理？另外虽然不是这个PR本身，但是Respoistory里面的aync方法也一起检查一下？
> > > ![image](https://user-images.githubusercontent.com/3387099/117571013-9c086e00-b081-11eb-8ef5-4fbc25306313.png)
> > 
> > 
> > 这里没有异步方法，我认为也这里可以不用异步方法～
> 
> MongoDB.Driver.Linq 异步方法在这个命名空间下 @huangkemeng

嗯嗯，已经改掉了~

2021-05-12 09:05 UTC, ppXD commented on src/SugarChat.MongoDb/MongoDbRepository.cs
> +            return FilteredQuery(predicate).AnyAsync();
也加上CancellationToken?

2021-05-12 09:05 UTC, ppXD commented on src/SugarChat.MongoDb/MongoDbRepository.cs
> +            return FilteredQuery(predicate).FirstOrDefaultAsync();
也加上CancellationToken?

2021-05-12 09:07 UTC, ppXD commented on src/SugarChat.MongoDb/MongoDbRepository.cs
> +            if (entities?.Any() == true)
为什么需要==true?

2021-05-12 09:11 UTC, huangkemeng commented on src/SugarChat.MongoDb/MongoDbRepository.cs
> +                    entity.CreatedDate = DateTimeOffset.Now;
> 是否在Entity的Constructor里初始化较好？

感觉不是很好，在Constructor里赋值，有时候这个字段并不总是等于当前时间，可能等于过去的某个时间

2021-05-12 09:12 UTC, huangkemeng commented on src/SugarChat.MongoDb/MongoDbRepository.cs
> +            return FilteredQuery(predicate).FirstOrDefaultAsync();
> 也加上CancellationToken?

嗯嗯。可以加上。

2021-05-13 03:14 UTC, mayuanyang approved these changes
LGTM

2021-05-13 03:49 UTC, merged