Unify response and exception handle
SugarChat/SugarChat pull request #20
Opened 2021-05-08 07:40 UTC by fanslead

2021-05-09 11:34 UTC, mayuanyang requested changes
这个PR需要继续讨论一下

2021-05-09 11:34 UTC, mayuanyang commented on src/SugarChat.Core/Common/CommonExceptionEnum.cs
> +    public enum CommonExceptionEnum : int
这里应该有点误会了
Unify response更多是说Mediator的Response，而不太是aspent的response，我们可以确保所有的request都经过mediator，但是确保不了所有的request都经过aspnet，比如说sugarchat很大可能跑在K8S上，而且通过sidecar的模式去跑，因此系统和系统之间不一定经过aspent，可以是Grpc，可以是Bus，可以Actor的TCP/IP，因此把filter做在aspent层面unify不了全局

估计可以做到全局的地方是在mediator的response上，比如
```
public interface ISugarChatResponse<T>: IResponse
{
  T Result{get;set;}
  BusinessException Error { get; set;}
}
```
因此不管经过哪个渠道，最后的结果能确保是ISugarChatResponse

另外就是CommonExceptionEnum是写不完的，因为可以有x个，比如 User not found = 5001， ImageTooLarge = 5002等，他们是一个BusinessException里面Code的一种。这些Code都是SugarChat里面的，如果遇到一些比如连接去数据库时网络断了，mongodb抛出了一个exception，这个不太是跟sugarchat的business相关的，这种情况下如果我们不把他当作是businessException的话，外界会直接得到一个直接的exception，而不是一个ISugarChatResponse里面有一个exception的对象（这个就要看我们是否要把他当作BusinessException了），

## 所以会有两种情况
- 如果不当作是BusinessExecption，而且request是来自aspent
调用方会得到一个http 5xx的response（正常的http response）

- 如果当作是BusinessException，而且request是来自aspent， 
调用方会得到一个ISugarChatResponse，里面的Error会是 
```
{
  code: 5003,
  message: "Internal server error, database connection lost, please try again later"
}
```
又或者是多语言
```
{
  code: 5003,
  message: "系统内部错误，数据库连接丢失了，请稍后再试"
}
```

总体来说，这个PR需要讨论一下

2021-05-09 11:34 UTC, mayuanyang commented on src/SugarChat.Core/Filters/WebApiResultFilter.cs
> +    public class WebApiResultFilter : ActionFilterAttribute
上面的comment包含了这部分，如果在mediator层面处理，估计就不需要这个了，当然也要看mediator处理的可行性

2021-05-09 11:34 UTC, mayuanyang commented on src/SugarChat.Core/Middlewares/ExceptionMiddleware.cs
> +namespace SugarChat.Core.Middlewares
同上

2021-05-09 11:34 UTC, mayuanyang commented on src/SugarChat.Core/Middlewares/MiddlewareExtension.cs
> +    public static class MiddlewareExtension
同上

2021-05-13 12:42 UTC, mayuanyang commented on src/SugarChat.Core/Exceptions/IBusinessException.cs
> +        int Code { get; set; }
这里也需要Message？

2021-05-13 13:43 UTC, BrianCodeman commented on src/SugarChat.Core/Exceptions/IBusinessException.cs
> +        int Code { get; set; }
这个应该从master合一下，那边已经不长这样了。

2021-05-14 04:20 UTC, ppXD commented on src/SugarChat.Core/Basic/ISugarChatResponse.cs
> +    public interface ISugarChatResponse : IResponse
是否有必要存在没有<T>的Response？

2021-05-14 04:22 UTC, ppXD commented on src/SugarChat.Core/Mediator/CommandHandlers/Groups/AddGroupCommandHandler.cs
> +    public class AddGroupCommandHandler : ICommandHandler<AddGroupCommand, ISugarChatResponse>
加个AddGroupResponse<>？

2021-05-14 05:46 UTC, fanslead commented on src/SugarChat.Core/Mediator/CommandHandlers/Groups/AddGroupCommandHandler.cs
> +    public class AddGroupCommandHandler : ICommandHandler<AddGroupCommand, ISugarChatResponse>
Command和Event类型的默认应该是无具体的Response的吧，用一个通用的Response应该比较适合

2021-05-19 00:46 UTC, ppXD commented on src/SugarChat.Core/Mediator/CommandHandlers/Groups/AddGroupCommandHandler.cs
> +    public class AddGroupCommandHandler : ICommandHandler<AddGroupCommand, ISugarChatResponse>
Mediator支持ICommandHandler<,>后，你使用的话，理应会有对应的Response比较好。

2021-05-19 00:46 UTC, ppXD commented on src/SugarChat.Core.Autofac/SugarChat.Core.Autofac.csproj
> +    <PackageReference Include="Mediator.Net.Autofac" Version="3.4.0-extendContract60" />
这个修改为"3.4.0-extendContract61"，新版本修复了一些bug。

2021-05-19 00:48 UTC, ppXD commented on src/SugarChat.Core/Basic/SugarChatResponse.cs
> +    public class SugarChatResponse : ISugarChatResponse
觉得没有必要存在不是Generic的Response，同理ISugarChatResponse<T>，一个就够了

2021-05-19 00:49 UTC, ppXD commented on src/SugarChat.Core/Filters/WebApiResultFilter.cs
> +    public class WebApiResultFilter : ActionFilterAttribute
可以删除该Filter

2021-05-19 00:50 UTC, ppXD commented on src/SugarChat.Core/Middlewares/ExceptionMiddleware.cs
> +namespace SugarChat.Core.Middlewares
删除该Middleware

2021-05-20 00:22 UTC, ppXD approved these changes
Approved

2021-05-20 00:23 UTC, mayuanyang approved these changes
LGTM

2021-05-20 00:34 UTC, merged