Feature refector dataProviders
SugarChat/SugarChat pull request #28
Opened 2021-05-12 16:20 UTC by BrianCodeman

1.Remove IRepository from All DataProviders
2.Move All Add/Delete method to DataProviders
2.Add Update Interface to DataProviders

2021-05-12 16:24 UTC, BrianCodeman commented
Due to "Update" implementation has not been reviewed and merged, the CI failed here. It's normal and should not be an issue. It will pass when IRepository Update brand been merged.

2021-05-13 07:46 UTC, BrianCodeman commented
Now the IRepository Update branch has merged and CI process has passed.

2021-05-13 12:48 UTC, mayuanyang requested changes
留了一点comment，另外需要加点tests？

2021-05-13 12:48 UTC, mayuanyang commented on src/SugarChat.Message/Commands/Users/UpdateUserCommand.cs
> +    public class UpdateUserCommand
需要implement ICommand

2021-05-13 12:48 UTC, mayuanyang commented on src/SugarChat.Message/Events/Users/UserUpdatedEvent.cs
> +    public class UserUpdatedEvent : EventBase
implement IEvent

2021-05-13 13:58 UTC, BrianCodeman commented on src/SugarChat.Message/Events/Users/UserUpdatedEvent.cs
> +    public class UserUpdatedEvent : EventBase
EventBase implements IEvent

2021-05-13 13:58 UTC, BrianCodeman commented on src/SugarChat.Message/Commands/Users/UpdateUserCommand.cs
> +    public class UpdateUserCommand
这个漏了，感谢review

2021-05-13 14:58 UTC, BrianCodeman commented
Tests will be added soon in next pr, and this one will mostly focus on defining resonable Service and Provider Interfaces, and part of implementation of course.

2021-05-14 04:26 UTC, ppXD approved these changes
Approved

2021-05-14 14:49 UTC, merged