webApi Mediator 管道配置
SugarChat/SugarChat pull request #33
Opened 2021-05-24 04:02 UTC by JERICHO-Z

2021-05-24 04:13 UTC, mayuanyang requested changes

2021-05-24 04:13 UTC, mayuanyang commented on src/SugarChat.Core.Autofac/SugarChatModule.cs
> +            builder.RegisterType(typeof(GroupUserDataProvider)).As(typeof(IGroupUserDataProvider));
这里可能需要加上LifetimeScope，另外也可以参考IService的注册模式，IDataProvider之类的，然后统一注册

2021-05-24 04:13 UTC, mayuanyang commented on src/SugarChat.WebApi/TestController.cs
> +    public class TestController : ControllerBase
名字需要改一下，GroupController，另外也看看这里的接口是否和腾讯的sdk一致，参考腾讯的就ok

2021-05-24 04:41 UTC, JERICHO-Z commented on src/SugarChat.WebApi/TestController.cs
> +    public class TestController : ControllerBase
这个没用的，就是试下跑不跑得通，可以删，接口在另外一条分支

2021-05-25 09:30 UTC, mayuanyang approved these changes
LGTM

2021-05-26 00:02 UTC, merged