add controller and handler related to message service
SugarChat/SugarChat pull request #50
Opened 2021-06-09 04:17 UTC by TiniGuo

2021-06-09 11:20 UTC, mayuanyang requested changes
名字需要处理一下，另外获取所有messages的接口没有分页？

2021-06-09 11:20 UTC, mayuanyang commented on src/SugarChat.WebApi/Controllers/MessageController.cs
> +        public async Task<IActionResult> GetAllUnreadToUser([FromQuery] GetAllUnreadToUserRequest request)
感觉名字需要修改一下
GetAllUnreadToUserRequest =》GetAllUnreadMessagesRequest
这个不用分页？

2021-06-09 11:20 UTC, mayuanyang commented on src/SugarChat.WebApi/Controllers/MessageController.cs
> +        public async Task<IActionResult> GetAllHistoryToUser([FromQuery] GetAllHistoryToUserRequest request)
GetAllHistoryToUserRequest => GetAllMessagesRequest
这个请求没有分页？

2021-06-09 11:20 UTC, mayuanyang commented on src/SugarChat.WebApi/Controllers/MessageController.cs
> +        public async Task<IActionResult> GetUnreadToUserFromGroup([FromQuery] GetUnreadToUserFromGroupRequest request)
GetUnreadToUserFromGroupRequest => GetUnreadMessagesFromGroupRequest

2021-06-09 11:20 UTC, mayuanyang commented on src/SugarChat.WebApi/Controllers/MessageController.cs
> +        public async Task<IActionResult> GetAllToUserFromGroup([FromQuery] GetAllToUserFromGroupRequest request)
GetAllToUserFromGroupRequest => GetAllMessagesFromGroupRequest
分页？

2021-06-10 08:11 UTC, TiniGuo commented on src/SugarChat.WebApi/Controllers/MessageController.cs
> +        public async Task<IActionResult> GetAllUnreadToUser([FromQuery] GetAllUnreadToUserRequest request)
这几个Service和Brain沟通后，觉得暂时没有想到具体的应用场景需要调用的地方，所以先把补的这几个MessageController中对应的Action方法先删除了

2021-06-10 08:21 UTC, TiniGuo commented on src/SugarChat.WebApi/Controllers/MessageController.cs
> +        public async Task<IActionResult> GetUnreadToUserFromGroup([FromQuery] GetUnreadToUserFromGroupRequest request)
目前和Brain沟通后先删除了

2021-06-10 08:21 UTC, TiniGuo commented on src/SugarChat.WebApi/Controllers/MessageController.cs
> +        public async Task<IActionResult> GetAllToUserFromGroup([FromQuery] GetAllToUserFromGroupRequest request)
目前和Brain沟通后先删除了

2021-06-10 23:22 UTC, mayuanyang commented on src/SugarChat.WebApi/Controllers/MessageController.cs
> +        public async Task<IActionResult> GetAllUnreadToUser([FromQuery] GetAllUnreadToUserRequest request)
有没有一个接口是GetUnreadMessageCount？

2021-06-10 23:23 UTC, mayuanyang commented on src/SugarChat.WebApi/Controllers/MessageController.cs
> +        public async Task<IActionResult> GetUnreadToUserFromGroup([FromQuery] GetUnreadToUserFromGroupRequest request)
这个不能删，yamimeal需要用 @TiniGuo

2021-06-10 23:23 UTC, mayuanyang commented on src/SugarChat.WebApi/Controllers/MessageController.cs
> +        public async Task<IActionResult> GetAllToUserFromGroup([FromQuery] GetAllToUserFromGroupRequest request)
这个不能删，yamimeal 需要用 @TiniGuo

2021-06-11 02:56 UTC, TiniGuo commented on src/SugarChat.WebApi/Controllers/MessageController.cs
> +        public async Task<IActionResult> GetAllUnreadToUser([FromQuery] GetAllUnreadToUserRequest request)
目前没有 我补一个

2021-06-11 13:10 UTC, mayuanyang approved these changes
LGTM

2021-06-11 14:34 UTC, merged