补全User、Group、Friend的Controller
SugarChat/SugarChat pull request #51
Opened 2021-06-09 05:26 UTC by JERICHO-Z

2021-06-10 01:14 UTC, mayuanyang reviewed
看看Code，Message等是否有默认值？

2021-06-10 01:14 UTC, mayuanyang commented on src/SugarChat.Core/Mediator/RequestHandlers/Users/GetCurrentUserRequestHandler.cs
> +            return new SugarChatResponse<UserDto>() { Code = 0, Message = "Success", Data = response.User };
如果ok的话，Code是等于0还是20000？是否有个默认值？，Message = “Success”是否可以设为默认？感觉不太统一

2021-06-10 01:22 UTC, JERICHO-Z commented on src/SugarChat.Core/Mediator/RequestHandlers/Users/GetCurrentUserRequestHandler.cs
> +            return new SugarChatResponse<UserDto>() { Code = 0, Message = "Success", Data = response.User };
我觉得是有的，但是不是在我这条分支上改。我之前在34的PR上面提了，没有改，现在所有的RequestHandler都是这样。

2021-06-10 01:35 UTC, JERICHO-Z commented on src/SugarChat.Core/Mediator/RequestHandlers/Users/GetCurrentUserRequestHandler.cs
> +            return new SugarChatResponse<UserDto>() { Code = 0, Message = "Success", Data = response.User };
我再跟Brian讨论一下

2021-06-10 08:44 UTC, BrianCodeman requested changes

2021-06-10 08:44 UTC, BrianCodeman commented on test/SugarChat.IntegrationTest/appsettings.json
> +    "ConnectionString": "mongodb://localhost:27017/",
这个地方指向mongoserver是有原因的，并不是每个开发者（比如我）都一定会在本地安装MongoDb，所以如果这个配置文件一定规定localhost的话，我就没办法连接数据库了，但是mongoserver的域名却可以指向任何地方，建议你修改一下本机的hosts文件，添加一条DNS映射（参见[https://github.com/SugarChat/SugarChat/#readme](https://github.com/SugarChat/SugarChat/#readme)），如: localhost    mongoserver
这样你一样可以连接到本机的mongodb

2021-06-12 00:22 UTC, mayuanyang approved these changes
LGTM

2021-06-12 01:05 UTC, merged