fix timeout about get conversion
SugarChat/SugarChat pull request #75
Opened 2021-11-05 06:37 UTC by JERICHO-Z

2021-11-22 12:16 UTC, mayuanyang requested changes
需要补测试，要么看看其他的comments是否合理？

2021-11-22 12:16 UTC, mayuanyang commented on src/SugarChat.Core/Services/Conversations/ConversationService.cs
> +                var lastMessage = _messageDataProvider.GetLastMessageBygGroupId(messageCountGroupByGroupId.GroupId);
这个方法是否需要await？

2021-11-22 12:16 UTC, mayuanyang commented on src/SugarChat.Core/Services/Conversations/ConversationService.cs
> +            var filterGroupIds = _groupDataProvider.GetGroupIdsByMessageKeyword(groupIds, request.SearchParms, request.IsExactSearch);
这个需要await？

2021-11-22 12:16 UTC, mayuanyang commented on src/SugarChat.Core/Services/Groups/GroupDataProvider.cs
> +            var bsonDocuments = _repository.GetAggregate<Domain.Message>(pipeline).ToList();
这个可否改为async？

2021-11-22 12:16 UTC, mayuanyang commented on src/SugarChat.Core/Services/Messages/IMessageDataProvider.cs
> +        IEnumerable<MessageCountGroupByGroupId> GetMessageCountGroupByGroupId(IEnumerable<string> groupIds, string userId, PageSettings pageSettings);
async比较好

2021-11-22 12:16 UTC, mayuanyang commented on src/SugarChat.Core/Services/Messages/MessageDataProvider.cs
> +            public Guid? _id { get; set; }
id可以为null？另外命名方式有点奇怪

2021-11-22 12:16 UTC, mayuanyang commented on src/SugarChat.Core/Services/Messages/MessageDataProvider.cs
> +        public IEnumerable<MessageCountGroupByGroupId> GetMessageCountGroupByGroupId(IEnumerable<string> groupIds, string userId, PageSettings pageSettings)
看看这里是否能async？

2021-11-23 08:34 UTC, JERICHO-Z commented on src/SugarChat.Core/Services/Messages/MessageDataProvider.cs
> +            public Guid? _id { get; set; }
group by需要指定一个相同的值，代码指定了null。现在再加多一层只显示Count。

2021-11-24 11:59 UTC, mayuanyang commented on src/SugarChat.WebApi/Controllers/MessageController.cs
> +        public async Task<IActionResult> GetUnreadMessageCount_Get([FromQuery] GetUnreadMessageCountRequest request)
这个命名规则有点奇怪

2021-11-24 11:59 UTC, mayuanyang commented on src/SugarChat.WebApi/Controllers/MessageController.cs
> +        public async Task<IActionResult> GetMessagesByGroupIds_Get([FromQuery] GetMessagesByGroupIdsRequest request)
命名规则？

2021-11-24 11:59 UTC, mayuanyang commented on src/SugarChat.Core/Services/Groups/GroupDataProvider.cs
> +        class _Group
命名？

2021-11-24 11:59 UTC, mayuanyang commented on src/SugarChat.Core/Services/Messages/IMessageDataProvider.cs
> +        Task<IEnumerable<MessageCountGroupByGroupId>> GetMessageCountGroupByGroupIdsAsync(IEnumerable<string> groupIds, string userId, PageSettings pageSettings, CancellationToken cancellationToken =
新的方法没有测试？

2021-11-25 02:25 UTC, JERICHO-Z commented on src/SugarChat.Core/Services/Groups/GroupDataProvider.cs
> +        class _Group
只系想内部用来接收序列化的结果

2021-11-25 21:08 UTC, mayuanyang approved these changes
LGTM

2021-11-26 01:57 UTC, merged